#!/bin/bash

if [ -f output.txt ]; then
	rm output.txt
fi

if [ -f log.txt ]; then
	rm log.txt
fi

if [ -f urls.txt ]; then
	rm urls.txt
fi

if [ -f crawled.txt ]; then
	rm crawled.txt
fi

if [ -f level0.txt ]; then 
	rm level*.txt
fi

if [ -d level0 ]; then
	rm -r level0
fi
