#!/bin/bash

seed='https://www.google.com'
log_file='log.txt'
output_file='output.txt'
url_file='urls.txt'

echo "$seed" > $url_file

while read url; do
	echo "Crawling $url"

	wget -o $log_file -O $output_file $url
	if [ $? -eq 0 ]; then
		grep -Eo "(http|https)://[A-Za-z0-9\./-]+" $output_file >> $url_file
	fi
done < $url_file
